namespace UnityEditor.PixyzPlugin4Unity.Toolbox
{
	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems {

		[MenuItem("Pixyz/Toolbox/Mesh/Decimate", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Decimate", priority = -20)]
		public static void A0f8214e4_8afd_4eef_8447_f148f0fbb1b4() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.DecimateAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Create Collider", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Create Collider", priority = -19)]
		public static void A71865a1e_a5c8_4233_b667_39d8652b5ecf() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateColliderAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Remove Colliders", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Remove Colliders", priority = -18)]
		public static void A911f9418_51c1_4d4b_9184_f7c9dff79ecf() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveCollidersAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Repair", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Repair", priority = -17)]
		public static void A989af537_4b70_44f5_a840_f6766b28bf24() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RepairMeshAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Z-Fighting", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Z-Fighting", priority = -15)]
		public static void A542f067d_41c7_4bc2_bdab_3d10878ccfde() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveZFightingAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Hidden", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Hidden", priority = -14)]
		public static void A058faf2d_eb60_46ab_8d6e_3f9ecf952520() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveHiddenAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Retopologize", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Retopologize", priority = -13)]
		public static void Ae550b156_7dba_46f6_97be_63d81f4bbb87() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RetopologizeAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Impostor", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Impostor", priority = -12)]
		public static void A24cc636f_1aff_481a_9952_67fbe3c5772f() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.BakeImpostor()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Billboard", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Billboard", priority = -12)]
		public static void Aa35c77a1_8d0f_40b3_8e02_2e9d87e9cd11() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.GenerateBillboardAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Merge", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Merge", priority = -11)]
		public static void Ad4ca8c84_90ef_4c74_adfd_0009775ca23f() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.Merge()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Combine", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Combine", priority = -10)]
		public static void Ae3098b18_ccab_462d_97c5_5908ffc177da() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CombineAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Replace by...", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Replace by...", priority = -9)]
		public static void Ac1d0d9e6_d7a3_4109_9e0d_91fba07c5d51() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ReplaceBy()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Explode", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Explode", priority = -8)]
		public static void Afec62071_752a_4b03_9fda_681a8a7c4035() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ExplodeSubmeshesAction()); }

		[MenuItem("Pixyz/Toolbox/Pivot/Move Pivot", priority = 22)]
		[MenuItem("GameObject/Pixyz/Pivot/Move Pivot", priority = -7)]
		public static void A472097b6_1e8f_4132_8cbc_58cbab7a20d5() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.MovePivotAction()); }

		[MenuItem("Pixyz/Toolbox/Normals/Flip Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Flip Normals", priority = -6)]
		public static void A001a6eef_9622_4e2d_9c14_4d239ee574fe() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.FlipNormals()); }

		[MenuItem("Pixyz/Toolbox/Normals/Create Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Create Normals", priority = -5)]
		public static void A91bf8c3f_1cc3_4edb_b821_6dc647a9d306() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateNormals()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs", priority = -4)]
		public static void A0bbe95e1_dc03_49df_b0b8_b99a070c5d67() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateUVs()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs for Lightmaps", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs for Lightmaps", priority = -3)]
		public static void A45d33563_fb1c_4b60_898a_10dbf332db7a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateLightmapUVs()); }

	}
}